steps:
  # 1. Build Docker image untuk backend
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/catatan", "."]
    dir: "backend"

  # 2. Push ke Container Registry / Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/catatan"]

  # 3. Deploy ke Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
      "run",
      "deploy",
      "be",
      "--image",
      "gcr.io/$PROJECT_ID/catatan",
      "--timeout",
      "1000s",
      "--port",
      "5000",
      "--region",
      "us-central1",
      "--platform",
      "managed",
      "--allow-unauthenticated",
      "--set-env-vars",
      "ACCESS_TOKEN_SECRET=${_ACCESS_TOKEN_SECRET},REFRESH_TOKEN_SECRET=${_REFRESH_TOKEN_SECRET},DB_HOST=${_DB_HOST},DB_NAME=${_DB_NAME},DB_PASSWORD=${_DB_PASSWORD},DB_USERNAME=${_DB_USERNAME}"
      ]

options:
  logging: CLOUD_LOGGING_ONLY
