FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY . .

# Gunakan PORT dari environment Cloud Run
ENV PORT=8080
EXPOSE 8080

CMD ["node", "index.js"]
